spring:
      #application:
                 #name: config-server
      #profiles:
              #active: native
      cloud:
           config:
                 server:
                       #native:
                             #search-locations: classpath:/config
                 git:
                    uri: 'https://github.com/sumanthshastry/config-repository.git'
                    clone-on-start: true
                    search-paths: 'config/{application}'                    
eureka:
      client:
            enabled: true
            service-url: 
                       default-zone: http://localhost:8761/eureka
server:
      port: 8888
      
management:
          security:
                  enabled: false
