spring:
      application:
                 name: configserver
      profiles:
              active: native
      cloud:
           config:
                 server:
                       native:
                             search-locations: classpath:/config
                             
eureka:
      client:
            enabled: true
            service-url: 
                       default-zone: http://localhost:8761/eureka
server:
      port: 8888
